/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CycleRouteImport } from './routes/cycle'
import { Route as L2RouteImport } from './routes/l2'
import { Route as L3RouteImport } from './routes/l3'
import { Route as L4RouteImport } from './routes/l4'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleRoute = CycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const L2Route = L2RouteImport.update({
  id: '/l2',
  path: '/l2',
  getParentRoute: () => rootRouteImport,
} as any)
const L3Route = L3RouteImport.update({
  id: '/l3',
  path: '/l3',
  getParentRoute: () => rootRouteImport,
} as any)
const L4Route = L4RouteImport.update({
  id: '/l4',
  path: '/l4',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cycle': typeof CycleRoute
  '/l2': typeof L2Route
  '/l3': typeof L3Route
  '/l4': typeof L4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cycle': typeof CycleRoute
  '/l2': typeof L2Route
  '/l3': typeof L3Route
  '/l4': typeof L4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cycle': typeof CycleRoute
  '/l2': typeof L2Route
  '/l3': typeof L3Route
  '/l4': typeof L4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cycle' | '/l2' | '/l3' | '/l4'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cycle' | '/l2' | '/l3' | '/l4'
  id: '__root__' | '/' | '/cycle' | '/l2' | '/l3' | '/l4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CycleRoute: typeof CycleRoute
  L2Route: typeof L2Route
  L3Route: typeof L3Route
  L4Route: typeof L4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle': {
      id: '/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof CycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l2': {
      id: '/l2'
      path: '/l2'
      fullPath: '/l2'
      preLoaderRoute: typeof L2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l3': {
      id: '/l3'
      path: '/l3'
      fullPath: '/l3'
      preLoaderRoute: typeof L3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l4': {
      id: '/l4'
      path: '/l4'
      fullPath: '/l4'
      preLoaderRoute: typeof L4RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CycleRoute: CycleRoute,
  L2Route: L2Route,
  L3Route: L3Route,
  L4Route: L4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
